### ISSUE TITLE
Error when exporting tags alf 3.4 UTF8

### ISSUE THREAD

**Issue by tamtamaouy** [wabson/share-import-export#14]
Hi,
when I try to export site TAGS from alfresco 3.4, i got this error : 
Export site tag information
/usr/lib/python2.6/urllib.py:1234: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  res = map(safe_map.__getitem__, s)
Log out (admin)
Traceback (most recent call last):
  File "export-site.py", line 257, in <module>
    main(sys.argv[1:])
  File "export-site.py", line 239, in main
    tagsData = sc.getSiteTagInfo(sitename, container)
  File "/home/onicl/share-import-export-master/shareclient/alfresco.py", line 505, in getSiteTagInfo
    result = self.doJSONGet('proxy/alfresco/slingshot/search?site=%s&term=&tag=%s&maxResults=1000&sort=&query=&repo=false' % (urllib.quote(unicode(siteId)), urllib.quote(unicode(tagName))))
  File "/usr/lib/python2.6/urllib.py", line 1234, in quote
    res = map(safe_map.__getitem__, s)
KeyError: u'\xe8'

thank in advance for any help or advise.

**Comment by tamtamaouy** [comment]
Hi Wabson,

I Wang to thank you first for this great tool :)
The solution for my issue is to change this line by adding .encode ("UTF-8") like this : 
result = self.doJSONGet('proxy/alfresco/slingshot/search?site=%s&term=&tag=%s&maxResults=1000&sort=&query=&repo=false' % (urllib.quote(unicode(siteId)), urllib.quote(tagName.encode("UTF-8")))))
