### ISSUE TITLE
alfresco.SurfRequestError

### ISSUE THREAD

**Issue by x-itec** [wabson/share-import-export#8]
Exporting a site (Alfresco 4.0)

python export-site.py http://127.0.0.1:8080/share/page/site/unternehmenshandbuch/dashboard bla.json --username=x--password=x --export-content

Log in (admin)
Get site information
Export all site content
Export documentLibrary
Log out (admin)
Traceback (most recent call last):
  File "export-site.py", line 254, in <module>
    main(sys.argv[1:])
  File "export-site.py", line 214, in main
    results = sc.exportAllSiteContent(sitename, siteContainers, includePaths, tempContainerName, async)
  File "/Volumes/DMS/xp/share-import-export/shareclient/alfresco.py", line 810, in exportAllSiteContent
    self.exportSiteContent(siteId, child['name'], includePaths, tempContainerName, async)
  File "/Volumes/DMS/xp/share-import-export/shareclient/alfresco.py", line 775, in exportSiteContent
    self.doJSONPost('proxy/alfresco/api/actionQueue?async=%s' % (str(async).lower()), json.dumps(actionDef))
  File "/Volumes/DMS/xp/share-import-export/shareclient/alfresco.py", line 163, in doJSONPost
    resp = self.doPost(path, dataStr, 'application/json; charset=UTF-8', method)
  File "/Volumes/DMS/xp/share-import-export/shareclient/alfresco.py", line 144, in doPost
    return self.doRequest(method, path, data, dataType)
  File "/Volumes/DMS/xp/share-import-export/shareclient/alfresco.py", line 132, in doRequest
    raise SurfRequestError(method, e.url, e.code, e.msg, e.hdrs, e.fp)
alfresco.SurfRequestError

**Comment by rr8779** [comment]
Hi, 2 minutes is the default http.socket.timeout.

if you take a look at your catalina.out, you should find a similar error :
webscripts.connector.RemoteClient
Error status 408 Read timed out
java.net.SocketTimeoutException: Read timed out

You will find this parameter if you look into the jar :
tomcat/webapps/alfresco/WEB-INF/lib/spring-webscripts-1.2.0-SNAPSHOT.jar
into :
org/springframework/extensions/webscripts/spring-webscripts-application-context.xml

- bean id="connector.remoteclient.abstract"
- property name="readTimeout"
- value = 120000 milliseconds = 2 minutes

You can simply modify the value into the jar file but a better approach is to override the bean setting by creating a file called :
tomcat/shared/classes/alfresco/web-extension/custom-slingshot-application-context.xml

Simply copy the content of spring-webscripts-application-context.xml and change the readTimeout value.

Don't forget to restart tomcat.

Regards,
Renaud

**Comment by ruria** [comment]
I had the same error, but after changing timeout value for alfresco webscripts, another timeout exception, now from alfresco.py script line 262 in share-import-export:

 return self.opener.open(req, timeout=self.timeout)

I´ve changed default timeout in ShareClient._init_ to something higher, and it worked.

**Comment by ehexin** [comment]
Exporting a site (Alfresco 4.2)
python export-site.py swsdp /opt2/share-import-export-master/115/swsdp.json --username=admin --password=admin --export-content


Log in (admin)
Get site information
Log out (admin)
Traceback (most recent call last):
  File "export-site.py", line 257, in <module>
    main(sys.argv[1:])
  File "export-site.py", line 193, in main
    sdata = sc.getSiteInfo(sitename, getMetaData, getMemberships, getPages, getDashboardConfig)
  File "/opt2/share-import-export-master/shareclient/alfresco.py", line 417, in getSiteInfo
    siteData['memberships'] = self.doJSONGet('proxy/alfresco/api/sites/%s/memberships' % (urllib.quote(unicode(siteId))))
  File "/opt2/share-import-export-master/shareclient/alfresco.py", line 279, in doJSONGet
    resp = self.doGet(path)
  File "/opt2/share-import-export-master/shareclient/alfresco.py", line 271, in doGet
    return self.doRequest("GET", path)
  File "/opt2/share-import-export-master/shareclient/alfresco.py", line 263, in doRequest
    raise SurfRequestError(method, e.url, e.code, e.msg, e.hdrs, e.fp)
alfresco.SurfRequestError: Spring Surf Error 500 (Internal Server Error)
...
...
...
</div>
   <div>


   </div>
</div>
</body>
</html>
wabson, can you help me....?

**Comment by ehexin** [comment]
</div>
   <div>


   </div>
</div>
</body>
</html>
wabson, can you help me?

**Comment by ehexin** [comment]
</div>
   <div>


   </div>
</div>
</body>
</html>
Hi wabson
Can you help me?

**Comment by ehexin** [comment]
-d

header: Content-Length: 1967
header: Connection: close
GET http://localhost:8080/share/proxy/alfresco/api/sites/swsdp/memberships
send: u'GET /share/proxy/alfresco/api/sites/swsdp/memberships HTTP/1.1\r\nAccept-Encoding: identity\r\nAccept-Language: en-gb,en;q=0.5\r\nConnection: close\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: ShareImportExport/1.0\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nHost: localhost:8080\r\nCookie: JSESSIONID=8B7E6BE08252B678D9C7277F0BD2DDCD; alfLogin=1428296551; alfUsername3=admin\r\n\r\n'
reply: 'HTTP/1.1 500 Internal Server Error\r\n'
header: Server: Apache-Coyote/1.1
header: Content-Type: text/html;charset=ISO-8859-1
header: Transfer-Encoding: chunked
header: Date: Mon, 06 Apr 2015 05:02:31 GMT
header: Connection: close
Log out (admin)
GET http://localhost:8080/share/page/dologout
